videodef/account/urls.py
from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("", views.home, name="home"),
    path("account/", views.account, name="account"),
    path("about/", views.about, name="about"),
    path("register/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("view/<str:user_id>/", views.view_other_user, name="view_other_user"),
]

videodef/chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path("", views.chats, name="chats"),
    path("<int:chat_id>/", views.chat_room, name="chat_room"),
    path("get/<str:user1_id>/<str:user2_id>/", views.get_chat, name="get_chat"),
]

videodef/child/urls.py
from django.urls import path

from . import views

app_name = "child"

urlpatterns = [
    path("my/", views.ChildListView.as_view(), name="my_children"),
    path("create/", views.ChildCreateView.as_view(), name="create_my_child"),
    path("edit/<int:pk>/", views.ChildUpdateView.as_view(), name="edit_my_child"),
    path(
        "delete/<int:pk>/", views.ChildDeleteView.as_view(), name="child_confirm_delete"
    ),
    path("view/<int:pk>/", views.ChildDetailView.as_view(), name="public_child_detail"),
]

videodef/game/urls.py
from django.urls import path
from . import views

app_name = "game"

urlpatterns = [
    path("", views.games, name="games"),
    path("my/", views.my_games_view, name="my_games"),
    path("puzzles/", views.puzzle_game, name="puzzle_game"),
    path("whiteboard/", views.whiteboard, name="whiteboard"),
    path("puzzles/save/", views.save_puzzle_view, name="save_puzzle"),
    path("puzzles/load/", views.load_puzzles_view, name="load_puzzles"),
    path(
        "puzzles/update/<str:game_id>/", views.update_puzzle_view, name="update_puzzle"
    ),
    path("delete/<str:game_id>/", views.delete_game_view, name="delete_game"),
]

videodef/main/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("account.urls", namespace="account")),
    path("chats/", include("chat.urls", namespace="chat")),
    path("videocall/", include("videocall.urls", namespace="videocall")),
    path("games/", include("game.urls", namespace="game")),
    path("resumes/", include("resume.urls", namespace="resume")),
    path("documents/", include("document.urls", namespace="document")),
    path("children/", include("child.urls", namespace="child")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videodef/resume/urls.py
from django.urls import path

from . import views

app_name = "resume"

urlpatterns = [
    path("my/", views.ResumeListView.as_view(), name="my_resumes"),
    path("create/", views.ResumeCreateView.as_view(), name="create_my_resume"),
    path("edit/<int:pk>/", views.ResumeUpdateView.as_view(), name="edit_my_resume"),
    path(
        "delete/<int:pk>/",
        views.ResumeDeleteView.as_view(),
        name="resume_confirm_delete",
    ),
    path("search/", views.PublicResumeListView.as_view(), name="public_resume_list"),
    path(
        "view/<int:pk>/", views.ResumeDetailView.as_view(), name="public_resume_detail"
    ),
]

videodef/videodef/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

videodef/chat/models.py
from django.db import models

from account.models import User


class SmallChat(models.Model):
    user1 = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="smallchat_user1_set",
        verbose_name="Пользователь 1",
    )
    user2 = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="smallchat_user2_set",
        verbose_name="Пользователь 2",
    )

    def __str__(self):
        return f"Чат между пользователями {self.user1} и {self.user2}"

    class Meta:
        verbose_name = "Чат"
        verbose_name_plural = "Чаты"


class Message(models.Model):
    chat = models.ForeignKey(
        SmallChat, related_name="messages", on_delete=models.CASCADE, verbose_name="Чат"
    )
    sender = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name="Отправитель"
    )
    content = models.TextField(max_length=1000, verbose_name="Содержимое")
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата отправления")

    def __str__(self):
        return f"{self.sender.username}: {self.content[:20]}"

    class Meta:
        verbose_name = "Сообщение"
        verbose_name_plural = "Сообщения"

videodef/chat/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseForbidden
from django.db.models import Q
from django.utils.timezone import now
from itertools import chain

from .models import SmallChat, Message
from account.models import User
from videocall.models import VideoCall


def chats(request):
    user_chats = SmallChat.objects.filter(
        user1=request.user
    ) | SmallChat.objects.filter(user2=request.user)
    chats_info = []
    for chat in user_chats:
        last_message = Message.objects.filter(chat=chat).order_by("timestamp").last()
        if last_message:
            if last_message.sender_id == request.user.unique_id:
                sender_name = "Вы"
            else:
                sender_name = User.objects.get(
                    unique_id=last_message.sender_id
                ).profile.first_name
            last_message_content = sender_name + ": " + last_message.content
        else:
            last_message_content = ""
        chats_info.append((chat, last_message_content))
    return render(request, "chat/chats.html", {"chats_info": chats_info})


def chat_room(request, chat_id):
    chat = get_object_or_404(SmallChat, id=chat_id)

    if request.user != chat.user1 and request.user != chat.user2:
        return HttpResponseForbidden("Вы не участник этого чата.")

    messages = chat.messages.all()
    calls = VideoCall.objects.filter(
        (
            Q(caller=chat.user1, receiver=chat.user2)
            | Q(caller=chat.user2, receiver=chat.user1)
        )
    )

    for msg in messages:
        msg.event_type = "message"
        msg.date = msg.timestamp.date()

    for call in calls:
        call.event_type = "call"
        call.date = call.started_at.date()

    events = sorted(
        chain(messages, calls),
        key=lambda x: x.timestamp if hasattr(x, "timestamp") else x.started_at,
    )

    return render(
        request,
        "chat/chat_room.html",
        {
            "chat": chat,
            "curr_date": now(),
            "events": events,
            "user": request.user,
        },
    )


def get_chat(request, user1_id, user2_id):
    if user1_id == user2_id:
        return redirect("chat:chats")

    user1 = get_object_or_404(User, unique_id=user1_id)
    user2 = get_object_or_404(User, unique_id=user2_id)

    chat = SmallChat.objects.filter(
        (Q(user1=user1) & Q(user2=user2)) | (Q(user1=user2) & Q(user2=user1))
    ).first()

    if not chat:
        chat = SmallChat.objects.create(user1=user1, user2=user2)

    return redirect("chat:chat_room", chat_id=chat.id)

videodef/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Видео дефектолог{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>
    {% block style %}{% endblock %}
</head>
<body>

    <header>
        <img src="{% static 'images/favicon.png' %}" style="width:130px;height:130px;" class="circle-img">
        <h1 class="circle-text">Видео дефектолог</h1>
    </header>

    <div id="user-data" data-user-id="{{ user_id }}"></div>

    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand small-circle-text" href="/">ГЛАВНАЯ</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
    
                    <!-- Общие вкладки -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:about' %}"><i class="bi bi-info-circle"></i> О проекте</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'game:games' %}"><i class="bi bi-controller"></i> Игры</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'chat:chats' %}"><i class="bi bi-chat-left-text"></i> Переписки</a>
                    </li>
    
                    {% if user.is_authenticated %}
                        <!-- Общие для преподавателя и родителя -->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'game:my_games' %}"><i class="bi bi-person-circle"></i> Мои игры</a>
                        </li>
    
                        {% if request.user.profile.role.name == 'Преподаватель' %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'document:my_documents' %}"><i class="bi bi-file-earmark-text"></i> Мои документы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'resume:my_resumes' %}"><i class="bi bi-file-earmark-text"></i> Мои резюме</a>
                            </li>
                        {% endif %}
    
                        {% if request.user.profile.role.name == 'Родитель' %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'child:my_children' %}"><i class="bi bi-person-lines-fill"></i> Мои дети</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'resume:public_resume_list' %}"><i class="bi bi-search"></i> Найти преподавателя</a>
                            </li>
                        {% endif %}
                    {% endif %}
    
                    <!-- Всегда доступно -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:account' %}"><i class="bi bi-person-circle"></i> Личный кабинет</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <div class="horizontal-container">
        {% block horizontal_left %}{% endblock %}
        <div class="container">
            {% include "messages.html" %}
            {% include "non_field_errors.html" %}

            <h2 class="display-4 text-center mb-4 page-name">{% block page_name %}{% endblock %}</h2>
            
            {% block content %}{% endblock %}
        </div>
        {% block horizontal_right %}{% endblock %}
    </div>

    {% block scripts %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/l10n/ru.js"></script>
    <script src="{% static 'js/date.js' %}"></script>
    <script>
        const user_id = "{{ request.user.unique_id }}";
    </script>
    <script src="{% static 'js/videocall/notify.js' %}"></script>
</body>
</html>

videodef/templates/chat.html
{% extends 'base.html' %}
{% block content %}
	<h2>Переписки</h2>
{% endblock %}

videodef/templates/edit-form.html
{% extends 'base.html' %}

{% block page_name %}Ваш профиль{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data" class="mb-3 mt-3">
        {% csrf_token %}

        {% if forms.profile_form.instance.photo %}
            <img src="{{ forms.profile_form.instance.photo.url }}" style="width:150px;height:150px;">
        {% else %}
            <img src="/media/avatars/default.png">
        {% endif %}
        <br>
        <div class="form-group">
            <p class="form-label">Изменить фото: </p>
            <input class="form-control" type="file" name="photo" id="id_photo" accept="image/*">
        </div>
        <br>
        <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" name="photo-clear" id="photo-clear_id" style="transform: scale(1.5)">
            <p class="form-label mx-2">Очистить фото</p>
        </div>
        

        <p class="form-label">Ваш ID: {{ unique_id }}</p>
        <p class="form-label">Дата вашей регистрации: {{ date_registr }}</p>

        {% include "default_field.html" with field=forms.user_form.username %}
        {% include "default_field.html" with field=forms.user_form.email %}
        {% include "default_field.html" with field=forms.user_form.phone_number %}
        {% include "default_field.html" with field=forms.user_form.password1 %}
        {% include "default_field.html" with field=forms.user_form.password2 %}

        {% include "default_field.html" with field=forms.profile_form.first_name %}
        {% include "default_field.html" with field=forms.profile_form.last_name %}
        {% include "default_field.html" with field=forms.profile_form.patronymic %}
        {% include "date_field.html" with field=forms.profile_form.date_birth %}
        {% include "default_field.html" with field=forms.profile_form.role %}
        {% include "default_field.html" with field=forms.profile_form.gender %}

        <button type="submit" class="btn btn-primary mb-3 mt-3">Отправить изменения</button>
    </form>
    <div class="mb-3 mt-3">
        <p><a href="logout">Выйти</a></p>
    </div>

    
{% endblock %}

videodef/templates/login-form.html
{% extends 'base.html' %}

{% block page_name %}Вход{% endblock %}
{% block content %}
	<form method="post" enctype="multipart/form-data" class="mb-3 mt-3">
		{% csrf_token %}
		{% include "default_field.html" with field=forms.login_form.identifier %}
		{% include "default_field.html" with field=forms.login_form.password %}
		
		<button type="submit" class="btn btn-primary mb-3 mt-3">Войти</button>

	</form>
	<div class="mb-3 mt-3">
        <p>Нет аккаунта? <a href="register">Зарегистрироваться</a></p>
    </div>
{% endblock %}

videodef/templates/messages.html
{% for message in messages %}
    {% if message.message != "Неверный логин или пароль" %}
        <div class="alert alert-warning">{{ message }}</div>
    {% endif %}
{% endfor %}

videodef/templates/non_field_errors.html
{% for form_name, form in forms.items %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger d-flex align-items-center mb-3 mt-3">{{ error }}</div>
    {% endfor %}
{% endfor %}

videodef/templates/register-form.html
{% extends 'base.html' %}

{% block page_name %}Регистрация{% endblock %}
{% block content %}
    <form method="post" enctype="multipart/form-data" class="mb-3 mt-3">
        {% csrf_token %}

        <div class="form-group">
            <label class="form-label" for="id_photo">{{ forms.register_form.photo.label_tag }}</label>
            <br>
            <input class="form-control" type="file" name="photo" id="id_photo" accept="image/*">
            <br>
            <img id="preview" src="{{ form.photo.value|default:'/media/avatars/default.png' }}" alt="Аватар" width="100" height="100" alt="Предпросмотр" style="width:150px;height:150px;">
        </div>
        <script>
            document.getElementById('id_photo').addEventListener('change', function(event) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    document.getElementById('preview').src = e.target.result;
                };
                reader.readAsDataURL(event.target.files[0]);
            });
        </script>

        {% include "default_field.html" with field=forms.register_form.first_name %}
        {% include "default_field.html" with field=forms.register_form.last_name %}
        {% include "default_field.html" with field=forms.register_form.patronymic %}
        {% include "date_field.html" with field=forms.register_form.date_birth %}
        {% include "default_field.html" with field=forms.register_form.role %}
        {% include "default_field.html" with field=forms.register_form.gender %}

        {% include "default_field.html" with field=forms.register_form.username %}
        {% include "default_field.html" with field=forms.register_form.email %}
        {% include "default_field.html" with field=forms.register_form.phone_number %}
        {% include "default_field.html" with field=forms.register_form.password1 %}
        {% include "default_field.html" with field=forms.register_form.password2 %}

        <button type="submit" class="btn btn-primary mb-3 mt-3">Зарегистрироваться</button>
    </form>
    <div class="mb-3 mt-3">
        <p>Уже есть аккаунт? <a href="login">Войти</a></p>
    </div>

    
{% endblock %}

videodef/templates/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <h2>Регистрация</h2>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <form method="post" class="mb-3 mt-3">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <p class="form-label">
                    {{ field.label_tag }}
                    {% if field.field.required %}
                        <span style="color: red; font-size: 23px;">*</span>
                    {% endif %}
                </p>
                {% if field.errors %}
                    {{ field|add_class:"form-control"|add_class:"is-invalid"}}
                {% else %}
                    {{ field|add_class:"form-control" }}
                {% endif %}
                {% for error in field.errors %}
                    <div class="alert alert-danger d-flex align-items-center mb-3 mt-3">{{ error }}</div>
                {% endfor %}
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary mb-3 mt-3">Зарегистрироваться</button>
    </form>
    <div class="mb-3 mt-3">
        <p>Уже есть аккаунт? <a href="{% url 'login' %}">Войти</a></p>
    </div>
{% endblock %}